version: '3'

services:
  db:
    image: mysql:8.0.13
    container_name: database
    ports:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=klarna
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - data-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin
    ports:
      - "80"

volumes:
  data-volume: {}